### PR TITLE
Fix ambient defintions for TS.

### PR DESCRIPTION
**Pull request by ScreamZ**
Hey,

I missed that the module was doing a `export default`, typings are wrong atm, this fix ambients types.

Can you release a patch accordingly, thanks :)

Regards

### CODE REVIEW

**Comment by ScreamZ** [comment]
@kkemple Up :)

**Comment by ScreamZ** [comment]
@kkemple Re-up ;)

**Comment by mitjade** [comment]
@ScreamZ I also have problems with dynamic scopes like:
```
import withAuth from 'graphql-auth';

const resolvers = {
  Query: {
    users: withAuth(
      (root: any, args: any, context: any, info: any) => { /* return scope based on resolver args */ },
      (root: any, args: any, context: any, info: any) => { ... }),
    ...
  }
}
```

**Comment by ScreamZ** [comment]
@mitjade Oh yes, I never used actually so I forgot, I'll fix this

**Comment by mitjade** [comment]
@ScreamZ Any chance of taking a look at the problems with dynamic scopes?

**Comment by ScreamZ** [comment]
@mitjade Yes, I'll look forward, I update this

**Pull request merged**
