### PR TITLE
Add Typescript ambient definitions.

### PR DESCRIPTION
**Pull request by ScreamZ**

### CODE REVIEW

**Comment by ScreamZ** [comment]
@kkemple ping

**Review by kkemple — APPROVED** [review]
this looks good! somehow missed this, apologies

**Comment by kkemple** [comment]
will merge and push out a new version tonight! thanks for adding this!

**Comment by ScreamZ** [comment]
Allright, reactive :p

Have a good afternoon :)

And thank you for that plugin

**Comment by mitjade** [comment]
@kkemple I too would really like this to get merged.

**Comment by kkemple** [comment]
published graphql-auth@0.2.3

**Pull request merged**
